/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MVC.View;

import BD.PlatillaBD;
import DTO.DTOMedico;
import DTO.DTOUsuario;
import Dao.Dao;
import MVC.Controller.CMedico;
import java.util.ArrayList;

/**
 *
 * @author josep
 */
public class ConsultarMedicos extends javax.swing.JInternalFrame {

    Dao DaoMedico;
    CMedico ControllerMedico;
    PlatillaBD bd;

    /**
     * Creates new form ConsultarClientes
     */
    public ConsultarMedicos(Dao dao, CMedico ControllerMedico, PlatillaBD bd) {
        initComponents();
        DaoMedico = dao;
        this.ControllerMedico = ControllerMedico;
        this.bd = bd;
        CargarTabla();
    }

    public void CargarTabla() {
        ArrayList<DTOMedico> x = ControllerMedico.LeerTodoS(bd);
        int z = 0;
        for (DTOMedico Lista : x) {
            int c = 0;
            this.tMedicos.setValueAt(Lista.getNumeroCedula(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getNombre(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getFechaNacimiento(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getTelefono(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getCorreo(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getCodigo(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getEspecialidad(), z, c);
            c++;
            this.tMedicos.setValueAt(Lista.getSalario(), z, c);
            c++;
            z++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMedicos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar médicos");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre Completo", "Fecha de Nacimiento", "Teléfono", "Correo electrónico", "Codigo Colegio", "Especialidad", "Salario"
            }
        ));
        jScrollPane1.setViewportView(tMedicos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tMedicos;
    // End of variables declaration//GEN-END:variables
}
